language: objective-c
os: osx
osx_image: xcode7.3

before install:
    - gem install xcpretty -N --no-ri --no-rdoc

env:
    matrix:
        - MATRIX_TARGET="-scheme CITest -sdk iphonesimulator9.3"

script:
    - set -o pipefail
    - xcodebuild clean test -project CITest.xcodeproj $MATRIX_TARGET GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty

addons:
    artifacts:
        paths:
        - $(find ~/Library/Developer/Xcode/DerivedData -type f -iname '*.log' | sed 's/.log/.log:/g')
